---
title: "Gapminder Analysis"
author: "Emma Kuan"
date: "1/28/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Gather data

```{r}
download.file(url="https://raw.githubusercontent.com/swcarpentry/r-novice-gapminder/gh-pages/_episodes_rmd/data/gapminder_data.csv", destfile="data/gapminder_data.csv")
gapminder <- read.csv("data/gapminder_data.csv")
```
```{r}
getwd <- read.csv("data/gapminder_data.csv")
```

```{r}
head(gapminder)
```
## plotting some data

```{r}
library(ggplot2)
```
### How does life expectancy change with GDP per capita?

```{r}
ggplot(data = gapminder, mapping= aes(x=gdpPercap, y=lifeExp)) + geom_point(size=1, alpha=0.25) +
  scale_x_log10() + 
  geom_smooth(method="lm", size=1.5)
```

### How does life expectancy change per year?

```{r}
ggplot(data = gapminder, mapping = aes(x=year, y=lifeExp, by=country)) + 
  geom_line(mapping = aes(color=continent)) +
  geom_point()
```

### How does life expectancy change per year in the americas?

```{r}
americas <- gapminder[gapminder$continent == "Americas",]
```
```{r}
ggplot(data=americas, mapping = aes(x=year, y=lifeExp, color=country)) + geom_line()
```

```{r}
americas <- gapminder[gapminder$continent == "Americas", ]
lifeExp_plot <- ggplot(data = americas, mapping = aes(x=year, y=lifeExp)) + 
  geom_line() +
  facet_wrap(~country)+
  theme(axis.text.x = element_text(angle = 90))
lifeExp_plot
```

```{r}
ggsave(plot=lifeExp_plot, filename = "lifeExp.png")
```

```{r}
ggplot(gapminder, aes(x=year, y=lifeExp, color=continent)) +
    geom_line(aes(by=country), alpha=0.2) + 
    stat_smooth(aes(by=continent), size=2)
```

```{r}
americas <- gapminder[gapminder$continent == "Americas", ]
lifeExp_plot <- ggplot(data = americas, mapping = aes(x=year, y=lifeExp)) + 
  geom_line() +
  facet_wrap(~country)+
  theme(axis.text.x = element_text(angle = 90))
```

### How does population affect gdpPercap in Asia?
```{r}
asia <- gapminder[gapminder$continent == "Asia",]
```

```{r}
Pop_plot <- ggplot(data = asia, mapping = aes(x=pop, y=gdpPercap, color=country)) + 
      geom_line()+
      geom_point(size=2, alpha=0.5)+
      geom_smooth(method = "lm")+
      scale_y_log10()+
      theme(axis.text.x = element_text(angle = 90))
Pop_plot
```
```{r}
ggsave(plot = Pop_plot, filename = "Pop.jpg")
```